app:
  ai:
    route-generation-url: ${AI_ROUTE_GENERATION_URL:}

spring:
  application:
    name: mediwalk-be

  config:
    import: optional:classpath:application-local.yaml

  datasource:
    url: jdbc:mysql://localhost:3306/mediwalk?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: root
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5

  flyway:
    enabled: true
    baseline-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        default_batch_fetch_size: 100
    open-in-view: false

firebase:
  enabled: false